addons:
  apt:
    packages:
     - libtk-img
     - mesa-common-dev
     - libglu1-mesa-dev
     - freeglut3-dev
     - libssl-dev
     - libcurl4-gnutls-dev
     - libxml2-dev
     - xvfb

sudo: false

os:
  - linux

apt_packages:
  - r-cran-rjava

language: r
before_install:
  - cd R
  - export DISPLAY=':99.0'
  - sudo $(which R) CMD javareconf
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1  &
  - R -q -e 'install.packages(c("loon","ggplot2","stringr", "patchwork", "gridExtra","magrittr", "dplyr", "rlang","testthat","knitr","rmarkdown",
                                "maps", "nycflights13", "hexbin", "zenplots"))'
  - R -q -e 'install.packages("BiocManager"); BiocManager::install(c("graph"), update = FALSE, ask=FALSE)'

cache: packages

r:
 - release
 - devel

after_success:
 - Rscript -e 'covr::codecov()'
